#pragma once

#include "CoreMinimal.h"
#include "E2GridRuntimeData.generated.h"

// ---------------------------------------------------
constexpr int32 INVALID_GRID_KEY = -1;

UENUM(meta = (Bitflags, UseEnumValuesAsMaskValuesInEditor = "true"))
enum class EE2GridFlags: int32
{
	NoFlags        = 0,
	CanWalkThrough = 1 << 1,
	IsWalkable     = 1 << 2,
};
ENUM_CLASS_FLAGS(EE2GridFlags);


USTRUCT(BlueprintType)
struct FE2GridCoord
{
	GENERATED_BODY()
	
	static E2GRID_API const FE2GridCoord INVALID_COORD;

	// --------------------------------------------
	
	FE2GridCoord operator += (const FE2GridCoord& Other)
	{
		X += Other.X;
		Y += Other.Y;
		Layer += Other.Layer;
		return *this;
	}

	// --------------------------------------------
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 X;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 Y;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 Layer = 0;	// Reserved not in used right now
};

USTRUCT(BlueprintType)
struct E2GRID_API FE2GridRuntimeData
{
	GENERATED_BODY()
	
public:
	FE2GridRuntimeData()
	: Coord(0, 0),
	  GridKey(INVALID_GRID_KEY),
	  GridFlags(0)
	{
	}

	void SetWalkable(const bool bInIsWalkable);
	
	bool IsWalkable() const;
	
	void SetCanWalkThrough(const bool bInCanWalkThrough);
	
	bool CanWalkThrough() const;	
	
protected:
	bool HasGridFlag(EE2GridFlags Flag) const;
	void SetGridFlag(EE2GridFlags Flag, const bool bEnabled);
	
public:
	UPROPERTY(BlueprintReadOnly)
	FE2GridCoord Coord;
	
	// Generally the key is generated by the formula: Key = X + Y * DimensionX 
	UPROPERTY(BlueprintReadOnly)
	int32 GridKey;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	bool bIsValid = true;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere, meta= (Bitmask, BitmaskEnum = "/Script/E2Grid.EE2GridFlags"))
	int32 GridFlags;
};

