// Fill out your copyright notice in the Description page of Project Settings.

#pragma once

#include "CoreMinimal.h"
#include "GameFramework/Actor.h"
#include "E2GridManager.generated.h"

class UE2GridVisualizeComponent;

// ---------------------------------------------------------
constexpr int32 INVALID_GRID_KEY = -1;

USTRUCT(BlueprintType)
struct FGridCoord
{
	GENERATED_BODY()
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 X;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 Y;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 Layer = 0;	// Reserved not in used right now
	
	FGridCoord operator += (const FGridCoord& Other)
	{
		X += Other.X;
		Y += Other.Y;
		Layer += Other.Layer;
		return *this;
	}
};

UCLASS(Blueprintable, BlueprintType)
class E2GRID_API UGridData : public UObject
{
	GENERATED_BODY()
	
public:
	UGridData()
	: Coord(0, 0),
	  GridKey(INVALID_GRID_KEY)
	{
	}
	
public:
	UPROPERTY(BlueprintReadOnly)
	FGridCoord Coord;
	
	// Generally the key is generated by the formula: Key = X + Y * DimensionX 
	UPROPERTY(BlueprintReadOnly)
	int32 GridKey;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	bool bIsValid = true;
};

UCLASS()
class E2GRID_API AE2GridManager : public AActor
{
	GENERATED_BODY()

public:
	AE2GridManager();
	
	UFUNCTION(BlueprintCallable, CallInEditor)
	void Generate();
	
	UFUNCTION(BlueprintCallable)
	void Clear();
	
	UFUNCTION(BlueprintCallable)
	bool IsValidGridKey(const int32 InGridKey) const;
	
	UFUNCTION(BlueprintCallable)
	bool IsValidGridCoord(const FGridCoord& InCoord) const;
	
	UFUNCTION(BlueprintCallable)
	bool IsGridMapEmpty();
	
	UFUNCTION(BlueprintCallable)
	const UGridData* GetGridData(const int32 InGridKey);
	
	// TODO: Move to grid coordinates utils
	UFUNCTION(BlueprintCallable)
	FGridCoord GetCoord(const int32 InGridKey);
	
	// UFUNCTION(BlueprintCallable)
	// FGridCoord GetCoordByWorldPosition(const FVector& InWorldPos);
	//
	// UFUNCTION(BlueprintCallable)
	// FGridCoord GetCoordByScreenPosition(const FVector& InScreenPos);
	
	UFUNCTION(BlueprintCallable)
	FVector GetWorldPosition(const FVector& InOrigin, const FGridCoord& InCoord);
	
#if WITH_EDITOR
	UFUNCTION(BlueprintCallable)
	void DrawGridMap(bool bClearOnly = false);
#endif

protected:
	virtual void OnConstruction(const FTransform& Transform) override;
	
	// Called when the game starts or when spawned
	virtual void BeginPlay() override;

public:
	// Called every frame
	virtual void Tick(float DeltaTime) override;
	
	// TODO: change grid map to independent data assets.
	void ForEachGridData(TFunctionRef<bool(TObjectPtr<UGridData> InGridData, const FVector& InWorldPosition)> InFunc);
	
#if WITH_EDITOR
	virtual void PostEditChangeProperty(FPropertyChangedEvent& PropertyChangedEvent) override;
	virtual void PostLoad() override;
#endif
	
// ---------------------------------------------------------
	
public:
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	TSubclassOf<UGridData> GridDataClass;
	
	// Indicate grid dimension (width, height)
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	FIntPoint GridDimension;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 GridSize = 100;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere, AdvancedDisplay)
	FVector BaseOffset = FVector::ZeroVector;
	
#if WITH_EDITORONLY_DATA
	UPROPERTY(BlueprintReadWrite, EditAnywhere, AdvancedDisplay)
	bool bDrawGridMap = false;
#endif
	
	UPROPERTY(VisibleAnywhere)
	TObjectPtr<UE2GridVisualizeComponent> GridVisualizeComponent; 
	
private:
	TMap<int32, TObjectPtr<UGridData>> GridMap;
};
