#pragma once

#include "CoreMinimal.h"
#include "E2GridRuntimeData.generated.h"

// ---------------------------------------------------
constexpr int32 INVALID_GRID_KEY = -1;

USTRUCT(BlueprintType)
struct FE2GridCoord
{
	GENERATED_BODY()
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 X;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 Y;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	int32 Layer = 0;	// Reserved not in used right now
	
	FE2GridCoord operator += (const FE2GridCoord& Other)
	{
		X += Other.X;
		Y += Other.Y;
		Layer += Other.Layer;
		return *this;
	}
};

UCLASS(Blueprintable, BlueprintType)
class E2GRID_API UE2GridRuntimeData : public UObject
{
	GENERATED_BODY()
	
public:
	UE2GridRuntimeData()
	: Coord(0, 0),
	  GridKey(INVALID_GRID_KEY)
	{
	}
	
public:
	UPROPERTY(BlueprintReadOnly)
	FE2GridCoord Coord;
	
	// Generally the key is generated by the formula: Key = X + Y * DimensionX 
	UPROPERTY(BlueprintReadOnly)
	int32 GridKey;
	
	UPROPERTY(BlueprintReadWrite, EditAnywhere)
	bool bIsValid = true;
};
